In [1]:
import numpy as np
import time

In [2]:
py_list=list(range(1_000_000))

start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(end-start)

brr=np.array(py_list)
start1=time.time()
sq_brr=brr**2
end1=time.time()
print(end1-start1)

if (end-start)>(end1-start1) :
    print("numpy is winner")
else:
    print("py_list is winner")


0.1374528408050537
0.002674102783203125
numpy is winner


In [3]:
import sys

print(f"python list {sys.getsizeof(py_list)*len(py_list)}")
print(f"numpy list {brr.nbytes}")

python list 8000056000000
numpy list 8000000


In [4]:
arr=np.array([1,2,4,5,7])
print(arr,type(arr),arr.dtype,arr.shape)
crr=np.array([1,2,3,'Hello'])
print(crr.dtype,crr.shape)

[1 2 4 5 7] <class 'numpy.ndarray'> int64 (5,)
<U21 (4,)


In [5]:
two_dimension=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dimension,two_dimension.shape,two_dimension.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2


In [6]:
#build-in function to create array

arr1=np.zeros((2,3))
print(arr1,arr1.shape)

arr2=np.ones((2,3),dtype="U21")
print(arr2)

arr3=np.full((2,3),"Hello") #create array with value given by user
print(arr3)

arr4=np.eye((3)) #identity matrix of size 3*3
print(arr4)

#arange(start,end,step)
arr5=np.arange(1,10,2)
print(arr5)

#linspace(start,end,size_of_array)
arr6=np.linspace(1,100,5)
print(arr6)


[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[['1' '1' '1']
 ['1' '1' '1']]
[['Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello']]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.    25.75  50.5   75.25 100.  ]


In [7]:
float_type=arr.astype(np.float64) #typecasting
print(float_type,float_type.dtype)

[1. 2. 4. 5. 7.] float64


In [8]:
#reshaping array

new_arr=np.array([[1,2,3],[4,5,6]])
reshape_arr=new_arr.reshape((3,2))
print(reshape_arr,reshape_arr.shape)

#1-d array

flattend_arr=new_arr.flatten()
print(flattend_arr)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [9]:
#indexing

print(flattend_arr[0])
print(two_dimension[0][1])

#fancy indexing
idx=[1,2,4] #array of index
print(flattend_arr[idx])

#boolean indexing
print(flattend_arr%2==0)
print(flattend_arr[flattend_arr%2==0])
print(arr[arr>2])

#slicing
#(start,end,step for skiping)
print(arr[:3:2])
print(arr[0:4:3])

1
2
[2 3 5]
[False  True False  True False  True]
[2 4 6]
[4 5 7]
[1 4]
[1 5]


In [10]:
#slicing creates view of array
#diff in py_list and numpy slicing

nums=[1,2,3,4,5]
sub_nums=nums[1:3]
sub_nums[0]=100
print(sub_nums,nums)

copy_arr=arr[1:3]
copy_arr[0]=100
print(copy_arr,arr)

#to avoid in changes in original numpy array use copy()
copy_arr2=arr[1:3].copy()
copy_arr2[1]=111
print(copy_arr2,arr)


[100, 3] [1, 2, 3, 4, 5]
[100   4] [  1 100   4   5   7]
[100 111] [  1 100   4   5   7]


In [11]:
#datatypes in numpy

print(copy_arr2.dtype)
copy_arr2=copy_arr2.astype(np.int16)
print(copy_arr2.dtype)
print(copy_arr2)

complex_arr1=np.array([3+5j , 5-2j])
complex_arr2=np.array([2-6j ,4-7j])
print(complex_arr1+complex_arr2)

object_arr=np.array([{"prime":"No","age":20}])
print(object_arr,object_arr.dtype,object_arr.shape)

int64
int16
[100 111]
[5.-1.j 9.-9.j]
[{'prime': 'No', 'age': 20}] object (1,)


In [12]:
#multidimensional array
arr_3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr_3d,arr_3d.shape,arr_3d.ndim)

sum_of_1d_arr=np.sum(arr)
print(sum_of_1d_arr)

sum_of_2d_arr=np.sum(two_dimension)
print(sum_of_2d_arr)

sum_rows=np.sum(two_dimension,axis=1)
print(sum_rows)

sum_columns=np.sum(two_dimension,axis=0)
print(sum_columns)

sum_of_3d=np.sum(arr_3d)
print(sum_of_3d)

sum_of_depth=np.sum(arr_3d,axis=0)
print(sum_of_depth)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2) 3
117
45
[ 6 15 24]
[12 15 18]
78
[[ 8 10]
 [12 14]
 [16 18]]


In [13]:
#slicing in 2d and 3d array

print(two_dimension)
print(two_dimension[0][0:3:2])

print(arr_3d)
print(arr_3d[:,0,:])
print(arr_3d[:,:,0])

arr_3d[0][2][1]=20
arr_3d[:,:,0]=100


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [36]:
#vectorisation and broadcasting
test_arr=np.array([1,2,3,4,5])
print(test_arr**2)
print(test_arr+10)

#broadcasting two array pe operation tb perform hogi jb unke dimension same ho ya column same ho aur koi ek array ka row 1ho

test_arr2=np.array([1,2,3,4,5])
print(test_arr+test_arr2)

test_2d=np.array([[1,2,3,4,5],[4,5,6,7,9]])
print(test_arr2+test_2d)

#vector normalistaion

mean=np.mean(test_2d)
std_dev=np.std(test_2d)
normalised_arr=(test_2d-mean)/std_dev
print(normalised_arr)

#sqrt func
print(np.sqrt(test_arr))

#aggregate math func

aggre_arr=np.array([1,2,3,4,5])
print(np.sum(aggre_arr))

print(np.prod(aggre_arr))
print(np.max(aggre_arr))
print(np.min(aggre_arr))

print(np.argmax(aggre_arr)) #index of max value
print(np.argmin(aggre_arr)) #index of min value

print(np.mean(aggre_arr))
print(np.std(aggre_arr))
print(np.var(aggre_arr)) #variance
print(np.median(aggre_arr))

#power func
print(np.square(aggre_arr))
print(np.sqrt(aggre_arr))
print(np.pow(aggre_arr,3))

#log func

print(np.log(aggre_arr))
print(np.log10(aggre_arr))
print(np.log2(aggre_arr))
print(np.exp(aggre_arr))

#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14)) #remove decimal digits

#set func
aggre_arr=np.insert(aggre_arr,2,4)
print(np.unique(aggre_arr))
print(np.sort(aggre_arr))

aggre_arr=np.insert(aggre_arr,6,[-3,-5])
print(np.abs(aggre_arr))



[ 1  4  9 16 25]
[11 12 13 14 15]
[ 2  4  6  8 10]
[[ 2  4  6  8 10]
 [ 5  7  9 11 14]]
[[-1.60356745 -1.15813205 -0.71269665 -0.26726124  0.17817416]
 [-0.26726124  0.17817416  0.62360956  1.06904497  1.95991577]]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
120
5
1
4
0
3.0
1.4142135623730951
2.0
3.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 2 3 4 4 5]
[1 2 4 3 4 5 3 5]
