In [1]:
import numpy as np

In [6]:

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

sum_row=np.sum(s,axis=0)
print(sum_row)
sum_col=np.sum(s,axis=1)
print(sum_col)
if(sum_row.all()==sum_col.all()):
    print("valid sudoku")
else:
    print("Invalid")    

[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]
valid sudoku


In [64]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
#1
print(data.shape)

#2
avg_age=data[:,0].copy()
print(f"avg age of students={(np.sum(avg_age))/len(data)}")

#3
math_marks=data[:,1].copy()
print(math_marks)

#4
print(np.max(data[:,2]))

#5
math_marks_greater_90=data[data[:,1]>90]
print(math_marks_greater_90)

#6
data[:,1]+=5
print(data)

#7
count=0
for i in avg_age:
 if i<19:
    count+=1
print(count)    

#8
print(f"avg marks in maths-{np.mean(data[:,1])}")
print(f"avg marks in science={np.mean(data[:,2])}")

#9
atleast_80_in_both=data[(data[:,1]>=80) & (data[:,2]>=80)]
print(atleast_80_in_both)

#10
data[data[:,2]<75,2]=0
print(data)

#11
print(np.max(data,axis=0))
print(np.argmax(data,axis=0))

##chatgpt1
ans1=data[(data[:,0]==18) & (data[:,2]>70)]
print(f"Here={ans1}")

##chatgpt2
data[data[:,1]<80,1]+=5
print(f"here={data}")

##chatgpt3
print(data)
avg_maths=np.mean(data[:,1])
data[(data[:,0]<19) & ((data[:,1]>=85) | (data[:,2]>=85)),1]=avg_maths
print(f"here {data[:,1]}")
data[(data[:,0]<19) & ((data[:,1])>=85 | (data[:,2]>=85)),2]=100
print(f"Here={data[:,2]}")

#12
print(data.size)

#13
arr100=np.array([1,2,3])
print(arr100+data)

#14
new_data=data.reshape(3,5)
print(new_data)

#15
arr_new=np.array([2,4,-3,8,-9,10,-2])
arr_new[arr_new<0]=0
even_arr=arr_new[arr_new %2==0]
print(arr_new,even_arr)

#16
arr_rand=np.random.rand(100)
mean1=np.mean(arr_rand)
std1=np.std(arr_rand)
normalised_arr=(arr_rand-mean1)/std1
print(normalised_arr)



(5, 3)
avg age of students=18.4
[85 92 76 65 90]
95
[[19 92 88]]
[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]
3
avg marks in maths-86.6
avg marks in science=83.2
[[19 97 88]
 [17 81 95]
 [20 95 85]]
[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
[20 97 95]
[4 1 2]
Here=[[18 90 78]]
here=[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 75  0]
 [20 95 85]]
[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 75  0]
 [20 95 85]]
here [87 97 87 75 95]
Here=[100  88 100   0  85]
15
[[ 19  89 103]
 [ 20  99  91]
 [ 18  89 103]
 [ 19  77   3]
 [ 21  97  88]]
[[ 18  87 100  19  97]
 [ 88  17  87 100  18]
 [ 75   0  20  95  85]]
[ 2  4  0  8  0 10  0] [ 2  4  0  8  0 10  0]
[-1.41286603 -0.52406522 -1.63236945  0.49099     0.21664872 -0.62902302
  1.09249922 -1.50235716  1.51881711 -1.43404201 -0.83197982  0.78919233
 -0.74511918 -0.29236837  1.52676469 -0.49429657 -0.43842219 -1.07998054
  0.51500256  0.59701845  0.27966615  1.23935252  1.0552569  -0.60119329
  1.14674689  0.5641848 